demo/booktest/urls.py
from django.contrib import admin
from django.urls import re_path
from booktest import views


urlpatterns = [
    re_path(r"^index2$", views.index, name="index"),  # 无参数反向解析
    re_path(r"^index2/(\d+)$", views.index, name="index"),  # 有位置参数的反向解析
    re_path(r"^index2/(?P<num>\d+)$", views.index, name="index"),  # 有关键字参数的反向解析
    re_path(r"^index$", views.index),
    re_path(r"^books$", views.show_books),
    re_path(r"^books/(\d+)$", views.show_heros),
    re_path(r"^create$", views.create),
    re_path(r"^delete(\d+)$", views.delete),
    re_path(r"^areas$", views.areas),
    re_path(r"^login_form$", views.login_form),
    re_path(r"^login_form_check$", views.login_form_check),
    re_path(r"^login_ajax$", views.login_ajax),
    re_path(r"^login_ajax_check$", views.login_ajax_check),
    re_path(r"^change_pwd$", views.change_pwd),
    re_path(r"^change_pwd_action$", views.change_pwd_action),
    re_path(r"^verify_code$", views.verify_code),
    re_path(r"^upload$", views.upload),
    re_path(r"^upload_handle$", views.upload_handle),
    re_path(r"^show_areas(?P<num>\d*)$", views.show_areas),
    re_path(r"^prov$", views.prov),
    re_path(r"^city/(?P<prov_id>\d+)$", views.city),
    re_path(r"^dis/(?P<dis_id>\d+)$", views.dis)

]

demo/demo/urls.py
from django.contrib import admin
from django.urls import re_path,include

urlpatterns = [
    re_path(r'admin/', admin.site.urls),
    re_path(r'^', include(("booktest.urls", "booktest"), namespace="booktest")),  # 配置反向解析，值一般是应用的名字
]

demo/booktest/models.py
from django.db import models

# Create your models here.


class BookInfoManager(models.Manager):
    """自定义添加图书管理器对象"""
    def create_book(self, b_title, b_pub_date):
        book = self.model()  # self.model可以获取当前调用模型类对象
        book.b_title = b_title
        book.b_pub_date = b_pub_date
        book.save()
        return book


class BookInfo(models.Model):
    """图书模型对象（一类）
    b_title: 图书名称
    b_pub_date: 出版日期
    b_read: 阅读量
    b_comment: 评论量
    isDelete: 逻辑删除
    """
    b_title = models.CharField(max_length=20)
    b_pub_date = models.DateField()
    b_read = models.IntegerField(default=0)
    b_comment = models.IntegerField(default=0)
    isDelete = models.BooleanField(default=False)
    books = BookInfoManager()

    def __str__(self):
        """修改模型对象默认返回名称"""
        return self.b_title


class HeroInfo(models.Model):
    """英雄模型对象（多类）
    h_name: 英雄姓名
    h_gender: 英雄性别
    h_comment: 英雄简介
    h_book: 英雄所属图书外键
    isDelete: 逻辑删除
    """
    h_name = models.CharField(max_length=20)
    h_gender = models.BooleanField(default=True)  # 默认是True：男性，False：女性
    h_comment = models.CharField(max_length=128)
    h_book = models.ForeignKey("BookInfo", on_delete=models.CASCADE)
    isDelete = models.BooleanField(default=False)

    def __str__(self):
        """修改模型对象默认返回名称"""
        return self.h_name


class AreaInfo(models.Model):
    """地区模型对象（自关联）"""
    a_title = models.CharField("区域名称", max_length=20)
    a_parent = models.ForeignKey("self", null=True, blank=True, on_delete=models.CASCADE)

    # 自定义字段名字
    def area_test(self):
        return self.a_title

    def parent(self):
        if not self.a_parent:
            return ""
        return self.a_parent.a_title

    # 下拉列表中输出的是对象的名称
    def __str__(self):
        return self.a_title

    # 自定义字段排序
    area_test.admin_order_field = "a_title"
    # 自定义字段重命名
    area_test.short_description = "区域名称"
    parent.short_description = "父级区域"
    parent.admin_order_field = "a_parent"


class PicTest(models.Model):
    '''图片上传模型'''
    good_pic = models.ImageField(upload_to="booktest")

demo/booktest/views.py
from datetime import date
import random
from django.conf import settings
from django.shortcuts import render,redirect
from django.http import HttpResponse,JsonResponse
from django.template import loader,RequestContext
from booktest.models import BookInfo,AreaInfo,PicTest
from PIL import Image, ImageDraw, ImageFont
from django.utils.six import BytesIO
from django.core.paginator import Paginator
from django.urls import reverse
# Create your views here.


def login_check(func):
    """检测是否登录的装饰器"""
    def wrapper_func(request, *args, **kwargs):
        # 如果cookie中有isLogin的session字段，直接返回对应视图定义的url，否则返回登录页面
        if request.session.get("isLogin"):
            print("==>测试代码<==")
            return func(request, *args, **kwargs)
        else:
            return redirect("/login_form")
    return wrapper_func


def index(request, *args):
    """index模板"""
    # # 1. 获取模板
    # template = loader.get_template("booktest/index.html")
    #
    # # 2. 定义上下文
    # context = {"title":"图书列表","list":range(15)}
    #
    # # 3. 渲染模板
    # res_html = template.render(context)
    #
    # # 4. 返回给浏览器html内容
    # return HttpResponse(res_html)
    return render(request, "booktest/index.html", {"title":"图书列表","list":range(15)})


def show_books(request):
    """显示图书信息"""
    # 1. 从model获取图书信息
    books_list = BookInfo.books.all()
    # 2. 渲染模板
    return render(request, "booktest/show_books.html", {"books": books_list})


def show_heros(request, b_id):
    """显示英雄信息"""
    # 1. 根据b_id从model获取图书信息
    book = BookInfo.books.get(id = b_id)

    # 2. 获取与图书关联的英雄信息
    heros = book.heroinfo_set.all()

    # 3. 渲染模板
    return render(request, "booktest/show_heros.html", {"book": book, "heros": heros})


def create(request):
    """新增图书"""
    # 1. 获取图书对象
    #book = BookInfo()

    # # 2. 添加数据
    # book.b_title = "流星蝴蝶剑"
    # book.b_pub_date = date(1987, 2, 12)
    #
    # # 3. 保存
    # book.save()

    # 使用自定义管理器操作数据库添加图书
    BookInfo.books.create_book("神雕侠侣", "2012-2-12")

    # 4. 重定向/index页面
    return redirect("/books")


def delete(request, b_id):
    """删除图书"""
    # 1. 根数b_id获取图书对象
    book = BookInfo.books.get(id=b_id)

    # 2. 删除对应图书
    book.delete()

    # 3. 重定向/index页面
    return redirect("/books")


def areas(request):
    """省市县案例"""

    # 4. 返回给浏览器信息
    return render(request, "booktest/areas.html")


def prov(request):
    """获取省的信息"""
    provinces = AreaInfo.objects.filter(a_parent__isnull=True)
    province_list = []  #  对象不能直接转为json格式
    for province in provinces:
        province_list.append((province.id, province.a_title))

    return JsonResponse({"data": province_list})


def city(request, prov_id):
    """获取市的信息"""
    cities = AreaInfo.objects.filter(a_parent=int(prov_id))
    city_list = []  #  对象不能直接转为json格式
    for city in cities:
        city_list.append((city.id, city.a_title))

    return JsonResponse({"data": city_list})


def dis(request, dis_id):
    """获取县的信息"""
    dises = AreaInfo.objects.filter(a_parent=int(dis_id))
    dis_list = []  #  对象不能直接转为json格式
    for dis in dises:
        dis_list.append((dis.id, dis.a_title))

    return JsonResponse({"data": dis_list})


def login_form(request):
    """form表单登录页面"""
    # 判断是否有isLogin字段session,如果有直接跳转修改密码页面，否则跳转登录页
    if request.session.get("isLogin"):
        return redirect("/change_pwd")
    else:
        return render(request, "booktest/login_form.html")


def login_form_check(request):
    """form表单验证"""
    # 1. 获取用户名和密码，验证码
    username = request.POST.get("username")
    password = request.POST.get("password")
    yzm = request.POST.get("yzm")  # form表单提交的验证码
    verify = request.session.get("verifycode")  # 服务器保存的验证码
    if yzm != verify:
        return redirect("/login_form")

    # 2. 验证用户名和密码,模拟username=rambo,password=123qwe
    if username == "rambo" and password == "123qwe":
        # 设置session标记已经登录的状态,设置用户名session
        request.session["isLogin"] = True
        request.session["username"] = username
        return redirect("/change_pwd")
    else:
        return redirect("/login_form")


def login_ajax(request):
    """ajax登录页面"""

    # 读取cookie
    cookies = request.COOKIES
    name = cookies["name"]

    # 把获取的cookie值传给login_ajax模板
    return render(request, "booktest/login_ajax.html", {"name": name})


def login_ajax_check(request):
    """ajax登录验证"""
    # 1. 获取用户名和密码
    username = request.POST.get("username")
    password = request.POST.get("password")

    # 设置cookie
    response = JsonResponse({"res": 1})
    response.set_cookie("name", "rambo", max_age=7 * 24 * 3600)

    # 2. 验证用户名和密码,模拟username=rambo,password=123qwe
    if username == "rambo" and password == "123qwe":
        # return JsonResponse({"res": 1})
        return response
    else:
        return JsonResponse({"res": 0})


@login_check
def change_pwd(request):
    """修改密码页面"""
    return render(request, "booktest/change_pwd.html")


@login_check
def change_pwd_action(request):
    """提交修改密码请求"""
    # 1. 获取修改的密码
    password = request.POST.get("password")

    # 2. 获取当前用户名
    username = request.session.get("username")

    # 3. 模拟提交数据库修改成功并且返回相应的数据
    return HttpResponse("%s 修改的密码是：%s" % (username, password))


def verify_code(request):
    """验证码"""
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(
        20, 100), 255)
    width = 100
    height = 30
    # 创建画面对象
    im = Image.new('RGB', (width, height), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, height))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    # 构造字体对象，ubuntu的字体路径为“/usr/share/fonts/truetype/freefont”
    font = ImageFont.truetype('/Users/lanbo/Library/Fonts/msyhbd.ttf', 23)
    # 构造字体颜色
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    draw.text((5, 2), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 2), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 2), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 2), rand_str[3], font=font, fill=fontcolor)
    # 释放画笔
    del draw
    # 存入session，用于做进一步验证
    request.session['verifycode'] = rand_str
    # 内存文件操作
    buf = BytesIO()
    # 将图片保存在内存中，文件类型为png
    im.save(buf, 'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(buf.getvalue(), 'image/png')


def upload(request):
    """上传图片页面"""
    return render(request, "booktest/upload.html")


def upload_handle(request):
    """图片处理"""
    # 1. 接收图片
    pic = request.FILES['pic']

    # 2. 创建文件来保存图片
    save_path = "%s/booktest/%s" % (settings.MEDIA_ROOT, pic.name)

    # 2. 读取下载图片
    with open(save_path, "wb") as f:
        for chunk in pic.chunks():
            f.write(chunk)

    # 3. 把图片相对路径存入数据库
    PicTest.objects.create(good_pic="booktest/%s" % pic.name)

    # 4. 返回成功状态
    return HttpResponse("OK")


def show_areas(request, num):
    """分页"""
    # 1. 获取地区数据
    areas = AreaInfo.objects.filter(a_parent__isnull=True)

    # 2. 分页，每页显示10条
    paginator = Paginator(areas, 10)

    # 3. 默认获取第一页内容
    if num is "":
        page = paginator.page(1)
    else:
        page = paginator.page(int(num))

    # 4. 把数据传给视图
    return render(request, "booktest/show_areas.html", {"page": page, "page": page})

demo/templates/booktest/areas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>省市县案例</title>
    <script src="static/js/jquery-1.12.4.min.js"></script>
</head>
<body>
<script>
    $(function () {
        $.get("/prov", function (data) {
            res = data.data
            $.each(res, function (index, item) {
                id = item[0]
                title = item[1]
                prov_str = "<option value='" + id + "'>" + title + "</option>"
                $("#prov").append(prov_str)
            })
        })
        $("#prov").change(function () {
            prov_id = $(this).val()
            $.get("/city/"+prov_id, function (data) {
                res = data.data
                $("#city").empty().append("<option value=\"\">---请选择市---</option>")
                $("#dis").empty().append("<option value=\"\">---请选择县---</option>")
                $.each(res, function (index, item) {
                    id = item[0]
                    title = item[1]
                    city_str = "<option value='" + id + "'>" + title + "</option>"
                    $("#city").append(city_str)
                })
            })
        })
        $("#city").change(function () {
            city_id = $(this).val()
            $.get("/dis/"+city_id, function (data) {
                res = data.data
                $("#dis").empty().append("<option value=\"\">---请选择县---</option>")
                $.each(res, function (index, item) {
                    id = item[0]
                    title = item[1]
                    dis_str = "<option value='" + id + "'>" + title + "</option>"
                    $("#dis").append(dis_str)
                })
            })
        })
    })
</script>
<select name="" id="prov">
    <option value="">---请选择省---</option>
</select>
<select name="" id="city">
    <option value="">---请选择市---</option>
</select>
<select name="" id="dis">
    <option value="">---请选择县---</option>
</select>
</body>
</html>

demo/templates/booktest/change_pwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码页面</title>
</head>
<body>
<form action="/change_pwd_action" method="post">
    {% csrf_token %}
    修改密码：<input type="password" name="password">
    <input type="submit" value="提交修改">
</form>
</body>
</html>

demo/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% load static from staticfiles %}
<body background="{% static 'images/python.png' %}">
<h1>{{title}}</h1>
{%for i in list%}
{{i}}<br>
{%endfor%}
</body>
</html>

demo/templates/booktest/login_ajax.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录ajax</title>
    <script src="/static/js/jquery-1.12.4.min.js"></script>
    <script>
        $(function () {
            $("#btnLogin").click(function () {
                $.ajax({
                    url: "/login_ajax_check",
                    type: "post",
                    dataType: "json",
                    data: {
                        username: $("#username").val(),
                        password: $("#password").val()
                    }
                }).success(function (data) {
                    if(data.res == "0") {
                        $("#errorMsg").show().html("用户名或密码错误")
                    }
                    else {
                        location.href = "/index"
                    }
                })
            })
        })
    </script>
    <style>
        #errorMsg {
            color: red;
            display: none;
        }
    </style>
</head>
<body>
<div>
    用户名：<input type="text" id="username" autocomplete="off" value="{{name}}"><br>
    密码：<input type="password" id="password" autocomplete="off"><br>
    <button type="text" id="btnLogin">登录</button>
    <div id="errorMsg"></div>
</div>
</body>
</html>

demo/templates/booktest/login_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
<a href="{% url 'booktest:index' %}">首页</a>
<a href="{% url 'booktest:index' 1 %}">首页</a>
<a href="{% url 'booktest:index' num=2 %}">首页</a>
<br><br>
<form method="post" action="/login_form_check">
    {% csrf_token %}
    用户名：<input type="text" name="username" autocomplete="off"><br>
    密码：<input type="password" name="password" autocomplete="off"><br>
    验证码：<input type="text" name="yzm">
    <img src="/verify_code" alt="">
    <a href="/login_form">重新获取验证码</a>
    <br>
    <button type="submit">登录</button>
</form>
</body>
</html>

demo/templates/booktest/show_areas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>分页</title>
</head>
<body>
<ul>
    {%for content in page%}
        <li>
            {{ content.a_title }}
        </li>
    {% endfor %}
</ul>
{% if page.has_previous %}
< <a href="show_areas{{ page.previous_page_number }}">上一页</a>
{% endif %}
{%for index in page.paginator.page_range %}
    {% if index == page.number %}
        {{index}}&nbsp;
    {% else %}
        <a href="show_areas{{ index }}">
            {{ index }}
        </a> &nbsp;
    {% endif %}
{% endfor %}
{% if page.has_next %}
<a href="show_areas{{ page.next_page_number }}">下一页</a> >
{% endif %}
</body>
</html>

demo/templates/booktest/show_books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图书信息</title>
</head>
<body>
<a href="/create">新增图书</a>
<h1>图书信息</h1>
<ul>
    {%for book in books%}
        <li>
            <a href="/books/{{book.id}}">
                {{book.b_title}}
            </a>----
            <a href="/delete{{book.id}}">删除</a>
        </li>
    {% endfor%}
</ul>
</body>
</html>

demo/templates/booktest/show_heros.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>英雄信息</title>
</head>
<body>
<h1>{{book.b_title}}</h1>
英雄信息：
<ul>
    {% for hero in heros %}
        <li>
            {{hero.h_name}}--{{hero.h_comment}}
        </li>
    {% empty %}
        <li>没有英雄信息</li>
    {% endfor %}
</ul>
</body>
</html>

demo/templates/booktest/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>上传图片</title>
</head>
<body>
<form action="upload_handle" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="pic"><br>
    <input type="submit" value="上传">
</form>
</body>
</html>